name: Go
on: [push, pull_request]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get influxdb image
        uses: flownative/action-docker-get-label@v1
        with:
          image: quay.io/influxdb/influxdb:2.0.0-beta
          registry_username: github
          registry_password: ${{ secrets.GITHUB_BOT_TOKEN }}
          registry_endpoint: https://docker.pkg.github.com/v2/

      - name: Test
        run: go test -v ./greeting/*.go